version: '3.8'

services:
  # 1. База данных (PostgreSQL)
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "127.0.0.1:5432:5432" # Доступно только через SSH-туннель
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - app_network

  # 2. Бэкенд (Python/Flask)
  api:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      FLASK_ENV: production
      BOT_TOKEN: ${BOT_TOKEN}
      YANDEX_FOLDER_ID: ${YANDEX_FOLDER_ID}
      YANDEX_API_KEY: ${YANDEX_API_KEY}
      VITE_ADMIN_IDS: ${VITE_ADMIN_IDS}
    volumes:
      - ./data:/app/public # Монтируем папку целиком, чтобы api мог создавать новые файлы (words_list.json)
      - ./cron_daily.py:/app/cron_daily.py # Скрипт ежедневных задач
    depends_on:
      - db
    networks:
      - app_network

  # 4. Планировщик (APScheduler)
  scheduler:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    command: python scheduler.py
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      FLASK_ENV: production
      BOT_TOKEN: ${BOT_TOKEN}
      YANDEX_FOLDER_ID: ${YANDEX_FOLDER_ID}
      YANDEX_API_KEY: ${YANDEX_API_KEY}
      VITE_ADMIN_IDS: ${VITE_ADMIN_IDS}
    volumes:
      - .:/app # Монтируем весь код, чтобы планировщик видел все скрипты
    depends_on:
      - db
    networks:
      - app_network

  # 3. Фронтенд (Nginx + React build)
  web:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data:/usr/share/nginx/html/data # Словарь доступен по /data/words_list.json
    depends_on:
      - api
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge